# Generated by Django 2.0.13 on 2019-05-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], db_index=True, max_length=3)),
                ('status', models.CharField(blank=True, choices=[('attended', 'attended'), ('noshow', 'noshow'), ('absent', 'absent')], db_index=True, max_length=32, null=True)),
                ('points', models.IntegerField(help_text='Points to be added (negative if you want to deduct)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('created', models.DateTimeField(db_index=True)),
                ('max_allowed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], db_index=True, max_length=3)),
                ('status', models.CharField(blank=True, choices=[('attended', 'attended'), ('noshow', 'noshow'), ('absent', 'absent')], db_index=True, max_length=32, null=True)),
                ('override_points', models.IntegerField(blank=True, help_text='This will be used to override points irrespective of status and rsvp', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member'),
        ),
    ]
