{
  "yes, attended": -1,  # confirmed went
  "yes, noshow": -300,  # said he will be here, but did not come
  "yes, absent": -2,    # said he will be there, but then the organizer selected "didn't go" instead of "noshow" (we have forgiven)

  "no, attended": -100, # said he won't be there, attended anyway
  "no, absent": 0,      # said he will be there, but has canceled in time
  "no, noshow": -250,   # said he will be here, canceled too late, got a penalty

  "yes, None": 0,       # said he will go, but we don't know what happened yet
  "no, None": 0,        # decided not to go before the event (did not click anything) or said he won't go and we don't know what happened yet
}
