{
  "yes, attended": 1,  # confirmed went (2019-03-13: doesn't work anymore, now it is "yes, None"
  "yes, noshow": 0,  # said he will be here, but did not come
  "yes, absent": 0,    # said he will be there, but then the organizer selected "didn't go" instead of "noshow" (we have forgiven)

  "no, attended": 0, # said he won't be there, attended anyway
  "no, absent": 0,      # said he will be there, but has canceled in time
  "no, noshow": 0,   # said he will be here, canceled too late, got a penalty

  "yes, None": 1,       # said he will go, but we don't know what happened yet UPDATE 2019-03-13 Meetup messed up their API AGAIN and doesn't output "attended" anymore, so we land here.
  "no, None": 0,        # decided not to go before the event (did not click anything) or said he won't go and we don't know what happened yet
}
