version: '2'

services:
  redis:
    image: redis:3-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis/data:/data

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data


  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: meetup_bot/app
    restart: always
    env_file: ./.env
    volumes:
      - backend-static:/srv/app/static
      - ./media:/srv/app/media
    links:
      - redis:redis
    depends_on:
      - redis
      - db

  
  celery-worker:
    image: meetup_bot/app
    env_file: ./.env
    environment:
      - DEBUG=off
    command: celery -A meetup_bot worker -l INFO --concurrency=4
    links:
      - redis:redis
    depends_on:
      - redis

  celery-beat:
    image: meetup_bot/app
    restart: always
    env_file: ./.env
    environment:
      - DEBUG=off
    command: celery -A meetup_bot beat -l INFO --schedule /tmp/celerybeat-schedule -f /tmp/logs/celery-beat.log
    volumes:
      - ./logs:/tmp/logs
    links:
      - redis:redis
    depends_on:
      - redis

  
  celery-flower:
    image: meetup_bot/app
    restart: always
    env_file: ./.env
    environment:
      - DEBUG=off
    command: celery flower --app=meetup_bot --broker="${CELERY_BROKER_URL}" --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
    depends_on:
      - celery-worker
    ports:
      - 5555:5555
  
  

  nginx:
    image: nginx:stable-alpine
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ./nginx/conf/default.template:/tmp/default.template
      - backend-static:/srv/static:ro
      - ./media:/srv/media:ro
      
      - ./letsencrypt/etc:/etc/letsencrypt
      - ./letsencrypt/data:/data/letsencrypt
      
    links:
      - app:app
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /tmp/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      
      - 443:443
      

volumes:
  backend-static:
