version: '2'

services:
  redis:
    image: redis:3-alpine
    command: redis-server --appendonly yes
    volumes:
    - ./redis/data:/data
    ports:
      - 8379:6379

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 8432:5432
